name: CICD step by step
on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run many steps
      run: echo "build job"
        
        
  test_job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
    - name: Run many steps
      run: echo "test job"

  deplpy_job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
    - name: Run many steps
      run: echo "deploy job"